var fileData=[
   {
     img:"Images/avi.svg",
     info:"my-file.avi",
     owner:"Admin",
     para1:"16/5/2021",
     para2:"12.5MB"
   },
   {
    img:"Images/eps.svg",
    info:"my-file.eps",
    owner:"Uploader",
    para1:"16/5/2021",
    para2:"2.7MB"
  },
  {
    img:"Images/psd.svg",
    info:"my-file.psd",
    owner:"Hamza",
    para1:"16/5/2021",
    para2:"15.1MB"
  },
  {
    img:"Images/dll.svg",
    info:"my-file.dll",
    owner:"Admin",
    para1:"16/5/2021",
    para2:"15.1MB"
  },
  {
    img:"Images/png.svg",
    info:"my-file.png",
    owner:"Designer",
    para1:"16/5/2021",
    para2:"1.5MB"
  },
  {
    img:"Images/pdf.svg",
    info:"my-file.pdf",
    owner:"Coder",
    para1:"16/5/2021",
    para2:"16.5MB"
  },
  {
    img:"Images/psd.svg",
    info:"my-file.psd",
    owner:"Hamza",
    para1:"16/5/2021",
    para2:"15.1MB"
  },
  {
    img:"Images/dll.svg",
    info:"my-file.dll",
    owner:"Admin",
    para1:"16/5/2021",
    para2:"15.1MB"
  },
  {
    img:"Images/png.svg",
    info:"my-file.png",
    owner:"Designer",
    para1:"16/5/2021",
    para2:"1.5MB"
  },
  {
    img:"Images/pdf.svg",
    info:"my-file.pdf",
    owner:"Coder",
    para1:"16/5/2021",
    para2:"16.5MB"
  },
  {
    img:"Images/avi.svg",
    info:"my-file.avi",
    owner:"Admin",
    para1:"16/5/2021",
    para2:"12.5MB"
  },
  {
   img:"Images/eps.svg",
   info:"my-file.eps",
   owner:"Uploader",
   para1:"16/5/2021",
   para2:"2.7MB"
 },
 {
    img:"Images/avi.svg",
    info:"my-file.avi",
    owner:"Admin",
    para1:"16/5/2021",
    para2:"12.5MB"
  },
  {
   img:"Images/eps.svg",
   info:"my-file.eps",
   owner:"Uploader",
   para1:"16/5/2021",
   para2:"2.7MB"
 },
 {
   img:"Images/psd.svg",
   info:"my-file.psd",
   owner:"Hamza",
   para1:"16/5/2021",
   para2:"15.1MB"
 },
 {
   img:"Images/dll.svg",
   info:"my-file.dll",
   owner:"Admin",
   para1:"16/5/2021",
   para2:"15.1MB"
 },
 {
    img:"Images/pdf.svg",
    info:"my-file.pdf",
    owner:"Coder",
    para1:"16/5/2021",
    para2:"16.5MB"
  },
  {
    img:"Images/psd.svg",
    info:"my-file.psd",
    owner:"Hamza",
    para1:"16/5/2021",
    para2:"15.1MB"
  },
  {
    img:"Images/avi.svg",
    info:"my-file.avi",
    owner:"Admin",
    para1:"16/5/2021",
    para2:"12.5MB"
  },
  {
   img:"Images/eps.svg",
   info:"my-file.eps",
   owner:"Uploader",
   para1:"16/5/2021",
   para2:"2.7MB"
 },
 {
   img:"Images/psd.svg",
   info:"my-file.psd",
   owner:"Hamza",
   para1:"16/5/2021",
   para2:"15.1MB"
 },
 {
   img:"Images/dll.svg",
   info:"my-file.dll",
   owner:"Admin",
   para1:"16/5/2021",
   para2:"15.1MB"
 },

]
var fileParent=document.getElementsByClassName("parent-item-file")[0]
fileData.forEach( (item )=> {
    fileParent.innerHTML+=   `
            <div class="file-item p-20">
                <i class="fa-solid fa-download"></i>
                <div class="file-info">
                    <img src="${item.img}" alt="">
                    <p class="my-20 fs-18">${item.info}</p>
                </div>
                <p class="c-gray">${item.owner}</p>
                <span class="line my-20"></span>
                <div class="flex-between c-gray">
                    <p>${item.para1}</p>
                    <p>${item.para2}</p>
                </div>
            </div>`
})